# Generated by Django 2.1.1 on 2019-07-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190730_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=False)),
                ('map_columns', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentRoom',
        ),
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=-1),
        ),
    ]
